### ISSUE TITLE
Clicking the pause button reloads the entire activity

### ISSUE THREAD

**Issue by GregSkl** [afollestad/easy-video-player#123]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Easy Video Player.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `0.3.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Oneplus`
 - Device Name: `3T`
 
###### Reproduction Steps

1. Open a video using this library
2. Click on the pause button (specifically pause, not play or anything else)

###### Expected Result
Well, I would expect the video to pause

###### Actual Result
The entire screen becomes white for a second and then the activity is reloaded, thus closing the video.
I don't have any logs because for some reason my logcat clears out everytime this happens and says "broken pipe"

###### Code

VideoPlayerActivity.java:
```package com.gregskl.haircompare;

import android.net.Uri;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.afollestad.easyvideoplayer.EasyVideoPlayer;

public class VideoPlayerActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);

        EasyVideoPlayer player = findViewById(R.id.player);
        String path = getIntent().getStringExtra(HaircutAdapter.PATH_KEY);
        player.setSource(Uri.parse(path));
    }
}```

activity_video_player.xml:
```<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.gregskl.haircompare.VideoPlayerActivity">

    <com.afollestad.easyvideoplayer.EasyVideoPlayer xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/player"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:evp_autoPlay="true"
        />

</android.support.constraint.ConstraintLayout>```

**Comment by GregSkl** [comment]
I managed to get my logcat to work properly and here's what it logs, first of all:
`files/example.mp4: java.io.FileNotFoundException: No content provider: /data/user/0/com.gregskl.example/files/example.mp4`

and:
```
                                                         --------- beginning of crash
11-11 13:40:40.589 14712-14712/com.gregskl.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.gregskl.example, PID: 14712
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'void com.afollestad.easyvideoplayer.EasyVideoCallback.onPaused(com.afollestad.easyvideoplayer.EasyVideoPlayer)' on a null object reference
                                                                             at com.afollestad.easyvideoplayer.EasyVideoPlayer.pause(EasyVideoPlayer.java:582)
                                                                             at com.afollestad.easyvideoplayer.EasyVideoPlayer.onClick(EasyVideoPlayer.java:868)
                                                                             at android.view.View.performClick(View.java:5669)
                                                                             at android.view.View$PerformClick.run(View.java:22549)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Could it be that pause doesn't work for some reason because the file is in my appliation's cache dir? But what I don't understand is how it manages to even play the video in the first place if it can't access it in my app's cache dir
