### ISSUE TITLE
java.lang.IllegalStateException in Sample App

### ISSUE THREAD

**Issue by chetanandroid** [afollestad/easy-video-player#127]
11-28 12:08:21.785 17522-17522/com.afollestad.easyvideoplayersample E/MediaPlayer: attachNewPlayer called in state 8
11-28 12:08:21.920 17522-17522/com.afollestad.easyvideoplayersample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.afollestad.easyvideoplayersample, PID: 17522
                                                                                      java.lang.IllegalStateException
                                                                                          at android.media.MediaPlayer._setDataSource(Native Method)
                                                                                          at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1001)
                                                                                          at android.media.MediaPlayer.setDataSource(MediaPlayer.java:954)
                                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.setSourceInternal(EasyVideoPlayer.java:397)
                                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.prepare(EasyVideoPlayer.java:426)
                                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.onSurfaceTextureAvailable(EasyVideoPlayer.java:653)
                                                                                          at android.view.TextureView.getHardwareLayer(TextureView.java:385)
                                                                                          at android.view.View.getDisplayList(View.java:13548)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.View.draw(View.java:14430)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                                                                                          at android.view.View.draw(View.java:14739)
                                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:534)
                                                                                          at android.view.View.getDisplayList(View.java:13588)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.View.draw(View.java:14430)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                                                                                          at android.view.View.getDisplayList(View.java:13580)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.View.draw(View.java:14430)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                                                                                          at android.view.View.getDisplayList(View.java:13580)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.View.draw(View.java:14430)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                                                                                          at android.view.View.getDisplayList(View.java:13580)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.View.draw(View.java:14430)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                                                                                          at android.view.View.getDisplayList(View.java:13580)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.View.draw(View.java:14430)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2387)
                                                                                          at android.view.View.draw(View.java:14739)
                                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:534)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2367)
                                                                                          at android.view.View.getDisplayList(View.java:13588)
                                                                                          at android.view.View.getDisplayList(View.java:13635)
                                                                                          at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
                                                                                          at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
                                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2728)
                                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2593)
                                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
                                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
                                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
                                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                                          at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                                          at android.os.Handler.handleCallback(Handler.java:808)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                                      	at dalvi
11-28 12:09:00.076 1038-1038/? E/ActionIcon: time changed: time = 20171128T120900Asia/Calcutta(2,331,19800,0,1511851140)

**Comment by EssamEmad** [comment]
This answer worked for me: https://stackoverflow.com/a/29628231/4504604

I have edited the source code to call mPlayer.reset() in the first line EasyVideoPlayer.setSourceInternal
