### ISSUE TITLE
java.util.MissingFormatArgumentException: Format specifier: C

### ISSUE THREAD

**Issue by jeancsanchez** [afollestad/easy-video-player#16]
I don't know, but probably the problem is on this code snippet:

`private static void LOG(String message, Object... args) {
        if (args != null)
            message = String.format(message, args);
        Log.d("EasyVideoPlayer", message);
    }`

**Android Log:**
java.util.MissingFormatArgumentException: Format specifier: C
                                                                               at java.util.Formatter.getArgument(Formatter.java:1111)
                                                                               at java.util.Formatter.doFormat(Formatter.java:1076)
                                                                               at java.util.Formatter.format(Formatter.java:1042)
                                                                               at java.util.Formatter.format(Formatter.java:1011)
                                                                               at java.lang.String.format(String.java:1803)
                                                                               at java.lang.String.format(String.java:1777)
                                                                               at com.afollestad.easyvideoplayer.EasyVideoPlayer.LOG(EasyVideoPlayer.java:853)
                                                                               at com.afollestad.easyvideoplayer.EasyVideoPlayer.prepare(EasyVideoPlayer.java:364)
                                                                               at com.afollestad.easyvideoplayer.EasyVideoPlayer.onSurfaceTextureAvailable(EasyVideoPlayer.java:576)
                                                                               at android.view.TextureView.getHardwareLayer(TextureView.java:370)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14545)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.draw(View.java:15638)
                                                                               at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14568)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14563)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.draw(View.java:15638)
                                                                               at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14568)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14563)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14563)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1377)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.draw(View.java:15638)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14568)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14563)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14563)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:14563)
                                                                               at android.view.View.getDisplayList(View.java:14590)
                                                                               at android.view.View.draw(View.java:15360)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
                                                                           	at android.view.View.updateDisplayListIfDirty(View.java:1

**Comment by afollestad** [comment]
Already fixed in a recent pull request

**Comment by shahabrauf18** [comment]
So how can i get the updated code, I am facing the same issue.
