### ISSUE TITLE
Not playing video, throws an Exception

### ISSUE THREAD

**Issue by Mahmudul531** [afollestad/easy-video-player#18]
When I use easyvideoplayer, an Exception is thrown.

``` gradle
stateLocked: wasEnabled = false, mIsEnabled = false, wasTouchExplorationEnabled = false, mIsTouchExplorationEnabled = false, wasHighTextContrastEnabled = false, mIsHighTextContrastEnabled = false
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager: java.lang.Throwable: setStateLocked
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.accessibility.AccessibilityManager.setStateLocked(AccessibilityManager.java:553)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.accessibility.AccessibilityManager.tryConnectToServiceLocked(AccessibilityManager.java:636)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.accessibility.AccessibilityManager.<init>(AccessibilityManager.java:226)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.accessibility.AccessibilityManager.getInstance(AccessibilityManager.java:206)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.View.setFlags(View.java:9843)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.ViewGroup.initViewGroup(ViewGroup.java:536)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.ViewGroup.<init>(ViewGroup.java:525)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.ViewGroup.<init>(ViewGroup.java:520)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.ViewGroup.<init>(ViewGroup.java:516)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.view.ViewGroup.<init>(ViewGroup.java:512)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.widget.FrameLayout.<init>(FrameLayout.java:119)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at com.android.internal.policy.impl.PhoneWindow$DecorView.<init>(PhoneWindow.java:2329)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at com.android.internal.policy.impl.PhoneWindow.generateDecor(PhoneWindow.java:3466)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3852)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2045)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:363)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at psd.braccl.eyedoora.VideoPlayer.onCreate(VideoPlayer.java:27)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.Activity.performCreate(Activity.java:6092)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.ActivityThread.access$800(ActivityThread.java:178)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.os.Handler.dispatchMessage(Handler.java:111)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.os.Looper.loop(Looper.java:194)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at android.app.ActivityThread.main(ActivityThread.java:5637)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at java.lang.reflect.Method.invoke(Native Method)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at java.lang.reflect.Method.invoke(Method.java:372)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
07-14 15:09:03.896 16504-16504/psd.braccl.eyedoora D/AccessibilityManager:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`
```

**Comment by afollestad** [comment]
Please use the issue template for future issues.

**Comment by afollestad** [comment]
Unfortunately there's not enough information here and nothing to reproduce.
