### ISSUE TITLE
Orination change issue

### ISSUE THREAD

**Issue by theAliAkhgar** [afollestad/easy-video-player#40]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Easy Video Player.
- [ ] I have given my issue a non-generic title.
- [- ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `0.2.10`
 - Device OS version: `6.0`
 - Device Manufacturer: `Genymotion`
 - Device Name: `Nexus `

I want to change the video player size on orination change but i get crash!

My code for orination change:

 @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {

            toolbar.setVisibility(View.GONE);
            RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            custom_video_player.setLayoutParams(layoutParams);
            custom_video_player.requestLayout();

        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){
            toolbar.setVisibility(View.VISIBLE);
            RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,200);
            custom_video_player.setLayoutParams(layoutParams);
            custom_video_player.requestLayout();
        }

    }

and the logcat:

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getVideoWidth()' on a null object reference
                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.onSurfaceTextureSizeChanged(EasyVideoPlayer.java:593)
                                                                          at android.view.TextureView.onSizeChanged(TextureView.java:329)

**Comment by theAliAkhgar** [comment]
i found the problem, its bcz of the reset() that i call on for videoplayer on activity start.
i call reset bcz video player starts buffering for no reason, what to do ?
