### ISSUE TITLE
Runtime exception on Android 4.4.4

### ISSUE THREAD

**Issue by dikhawk** [afollestad/easy-video-player#60]
- [+] I have verified there are no duplicate active or recent bugs, questions, or requests
- [+] I have verified that I am using the latest version of Easy Video Player.
- [+] I have given my issue a non-generic title.
- [+] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `0.2.13`
 - Device OS version: `4.4.4`
 - Device Manufacturer: `Genymotion`
 - Device Name: `Genymotion`

Also, please wrap Java with correct syntax highlighting.

```java
public class VideoPlayerActivity extends AppCompatActivity implements EasyVideoCallback {

    public static final String VIDEO_URL = "video_url";
    private EasyVideoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);
        if (Build.VERSION.SDK_INT < 16) {
            getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                    WindowManager.LayoutParams.FLAG_FULLSCREEN);
        } else {
            View decorView = getWindow().getDecorView();
            int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN;
            decorView.setSystemUiVisibility(uiOptions);
        }

        String videoUrl = getIntent().getStringExtra(VIDEO_URL);

        player = (EasyVideoPlayer) findViewById(R.id.evp_player);
        player.setAutoPlay(true);
        player.setCallback(this);

        player.setSource(Uri.parse(videoUrl));
    }

    @Override
    protected void onPause() {
        player.pause();
        super.onPause();
    }


    @Override
    public void onStarted(EasyVideoPlayer player) {
        
    }

    @Override
    public void onPaused(EasyVideoPlayer player) {

    }

    @Override
    public void onPreparing(EasyVideoPlayer player) {
    }

    @Override
    public void onPrepared(EasyVideoPlayer player) {

    }

    @Override
    public void onBuffering(int percent) {

    }

    @Override
    public void onError(EasyVideoPlayer player, Exception e) {

    }

    @Override
    public void onCompletion(EasyVideoPlayer player) {

    }

    @Override
    public void onRetry(EasyVideoPlayer player, Uri source) {

    }

    @Override
    public void onSubmit(EasyVideoPlayer player, Uri source) {

    }
```

<?xml version="1.0" encoding="utf-8"?>
<com.afollestad.easyvideoplayer.EasyVideoPlayer xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/evp_player"
    android:layout_width="match_parent"
    android:layout_height="match_parent" /> 

###### Reproduction Steps

1. Launch Activity

###### Expected Result

Launched activity

###### Actual Result
error
10-16 12:08:53.266 2401-2401/com.growdiaries.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.growdiaries.android, PID: 2401
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.growdiaries.android/com.growdiaries.android.ui.VideoPlayerActivity}: android.view.InflateException: Binary XML file line #46: Error inflating class ImageButton
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: android.view.InflateException: Binary XML file line #46: Error inflating class ImageButton
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                           at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:743)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:763)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                           at com.growdiaries.android.ui.VideoPlayerActivity.onCreate(VideoPlayerActivity.java:24)
                                                                           at android.app.Activity.performCreate(Activity.java:5231)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: android.content.res.Resources$NotFoundException: File res/drawable/evp_action_restart.xml from drawable resource ID #0x7f02009e
                                                                           at android.content.res.Resources.loadDrawable(Resources.java:2096)
                                                                           at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                           at android.widget.ImageView.<init>(ImageView.java:129)
                                                                           at android.widget.ImageButton.<init>(ImageButton.java:87)
                                                                           at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57)
                                                                           at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53)
                                                                           at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1013)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1072)
                                                                           at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                           at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:743) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:763) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                           at com.growdiaries.android.ui.VideoPlayerActivity.onCreate(VideoPlayerActivity.java:24) 
                                                                           at android.app.Activity.performCreate(Activity.java:5231) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                                           at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                                           at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                                           at android.content.res.Resources.loadDrawable(Resources.java:2092)
                                                                           at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                           at android.widget.ImageView.<init>(ImageView.java:129) 
                                                                           at android.widget.ImageButton.<init>(ImageButton.java:87) 
                                                                           at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57) 
                                                                           at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53) 
                                                                           at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1013) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1072) 
                                                                           at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                           at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:743) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:763) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                           at com.growdiaries.android.ui.VideoPlayerActivity.onCreate(VideoPlayerActivity.java:24) 
                                                                           at android.app.Activity.performCreate(Activity.java:5231) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by neytireyqa** [comment]
Definitely bug in <API19; Downgrading to version 0.2.10 solves the issue for now. [tested on Emulator API16]
