### ISSUE TITLE
Resource is not released

### ISSUE THREAD

**Issue by rubengees** [afollestad/easy-video-player#65]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Easy Video Player.
- [X] I have given my issue a non-generic title.
- [X] I have read over the documentation (before asking questions on how to do something).

 - Easy Video Player version: `0.3.0`
 - Device OS version: `7.1`
 - Device Manufacturer: `OnePlus`
 - Device Name: `3`

The underlying `TextureView` seems not to be released upon destruction of the `Activity`.  
I get the following stacktrace:

```
E/StrictMode: A resource was acquired at attached stack trace but never released.
See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'release' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at android.view.Surface.setNativeObjectLocked(Surface.java:490)
at android.view.Surface.<init>(Surface.java:164)
at com.afollestad.easyvideoplayer.EasyVideoPlayer
                                 .onSurfaceTextureAvailable(EasyVideoPlayer.java:648)
at android.view.TextureView.getHardwareLayer(TextureView.java:389)
at android.view.TextureView.draw(TextureView.java:338)
at android.view.View.updateDisplayListIfDirty(View.java:16173)
at android.view.View.draw(View.java:16957)
[...]
```
 
This seems to be found by `StrictMode`.
You can get this exception in the `sample` by adding the following:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    if (BuildConfig.DEBUG) {
        StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                .detectAll()
                .penaltyLog()
                .penaltyDialog()
                .build());
        StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                .detectAll()
                .penaltyLog()
                .build());
    }

    player = (EasyVideoPlayer) findViewById(R.id.player);
    assert player != null;
    player.setCallback(this);
    // All further configuration is done from the XML layout.
}
```

This even happens by explicitly calling `release` on the player:

```java
@Override
protected void onDestroy() {
    super.onDestroy();
    player.release();
}
```

**Comment by afollestad** [comment]
You shouldn't rely on `onDestroy()`, there are cases when it isn't used. 

I always use this:

```java
@Override
public void onPause() {
    super.onPause();
    if (isFinishing())
            player.release();
}
``2

**Comment by rubengees** [comment]
Same error.

**Comment by afollestad** [comment]
Sorry, I probably can't help you then.

Never experienced any problems in a few production apps that are using this.

**Comment by rubengees** [comment]
Yes, it works without problems, I just wanted to notify you that this is a thing.
