### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by powerthazan** [afollestad/easy-video-player#69]
###### Include the following:
 - Easy Video Player version: `0.3.0`
 - Device OS version: `API 24`
 - Device Manufacturer: `Samsung`
 - Device Name: `GT-I9295`

Error Message: 

```java
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.View.setFitsSystemWindows(boolean)' on a null object reference
```

Raw Log: 
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFitsSystemWindows(boolean)' on a null object reference
       at android.support.v4.view.ViewCompatICS.setFitsSystemWindows(SourceFile:55)
       at android.support.v4.view.ViewCompat$ICSViewCompatImpl.setFitsSystemWindows(SourceFile:1411)
       at android.support.v4.view.ViewCompat.setFitsSystemWindows(SourceFile:3000)
       at com.afollestad.easyvideoplayer.EasyVideoPlayer.setFullscreen(SourceFile:1062)
       at com.afollestad.easyvideoplayer.EasyVideoPlayer.access$000(SourceFile:57)
       at com.afollestad.easyvideoplayer.EasyVideoPlayer$3.onAnimationEnd(SourceFile:484)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1136)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:804)
       at android.view.Choreographer.doCallbacks(Choreographer.java:607)
       at android.view.Choreographer.doFrame(Choreographer.java:575)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:790)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5830)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

**Comment by ITDreamSKY** [comment]
Hi, were you able to solve this issue?

**Comment by ITDreamSKY** [comment]
line 1062 add
if(mControlsFrame==null){
return;
}
