### ISSUE TITLE
Nullpointer exception 

### ISSUE THREAD

**Issue by kancic** [afollestad/easy-video-player#72]
- Easy Video Player version: `0.3.0`

Line 582 in EasyVideoPlayer.java
```java
        mCallback.onPaused(this);
```

Needs
```java
        if (mCallback != null) mCallback.onPaused(this);
```

Because without it you get
```java
java.lang.NullPointerException: Attempt to invoke interface method 'void com.afollestad.easyvideoplayer.EasyVideoCallback.onPaused(com.afollestad.easyvideoplayer.EasyVideoPlayer)' on a null object reference
                                                                                    at com.afollestad.easyvideoplayer.EasyVideoPlayer.pause(EasyVideoPlayer.java:582)
                                                                                    at com.afollestad.easyvideoplayer.EasyVideoPlayer.onClick(EasyVideoPlayer.java:868)
                                                                                    at android.view.View.performClick(View.java:5637)
                                                                                    at android.view.View$PerformClick.run(View.java:22429)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mandadimuralidharreddy** [comment]
Same thing happening in line no 833
mCallback.onClickVideoFrame(easyVideoPlayer);
to 
if (mCallback != null) mCallback.onClickVideoFrame(easyVideoPlayer);
