### ISSUE TITLE
Could not initialize class android.media.MediaPlayer

### ISSUE THREAD

**Issue by tachang** [afollestad/easy-video-player#77]
- Easy Video Player version: `0.3.0`

 
###### Reproduction Steps

```
            <com.afollestad.easyvideoplayer.EasyVideoPlayer
                android:id="@+id/videoPlayer"
                android:padding="1dp"
                android:layout_width="240dp"
                android:layout_height="wrap_content"
                />
```

###### Expected Result

I can see the layout visually.

###### Actual Result

```
java.lang.NoClassDefFoundError: Could not initialize class android.media.MediaPlayer
	at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:867)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by tachang** [comment]
```
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:design:25.1.0'
```

**Comment by tachang** [comment]
I get this with the sample project as well.

**Comment by tachang** [comment]
```
public class MediaPlayer {

...

    public MediaPlayer() {
        throw new RuntimeException("Stub!");
    }

```

**Comment by afollestad** [comment]
That's an Android framework class.

**Comment by Thanhktm** [comment]
Happened when I update to Android Studio 2.3.3.

**Comment by devaniumesh** [comment]
I have same issue

**Comment by smaugho** [comment]
Hi, same issue here, any solution?

**Comment by inialdan** [comment]
Hi, i have same issue, any solution to reach it?
