### ISSUE TITLE
Loading a second video error

### ISSUE THREAD

**Issue by Johannes11833** [afollestad/easy-video-player#83]
I have the probelm that when I load a second video after having played one before, that its does not show the progress circle and also shows a frame from the first video before it starts to play. Is there a way to fix this or am I missing something? 
I am using `play.stop()` and `player.reset()` before loading a new video.

**Comment by quangctkm9207** [comment]
I got the same problem.
Previously, I used ver 0.2.9 and it worked without this issue.

*Detail*:
`        java.lang.IllegalStateException
                                                                                   at android.media.MediaPlayer._setDataSource(Native Method)
                                                                                   at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1025)
                                                                                   at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1009)
                                                                                   at android.media.MediaPlayer.setDataSource(MediaPlayer.java:906)
                                                                                   at android.media.MediaPlayer.setDataSource(MediaPlayer.java:874)
                                                                                   at com.afollestad.easyvideoplayer.EasyVideoPlayer.setSourceInternal(EasyVideoPlayer.java:419)
                                                                                   at com.afollestad.easyvideoplayer.EasyVideoPlayer.prepare(EasyVideoPlayer.java:431)
                                                                                   at com.afollestad.easyvideoplayer.EasyVideoPlayer.onSurfaceTextureAvailable(EasyVideoPlayer.java:652)
                                                                                   at android.view.TextureView.getHardwareLayer(TextureView.java:385)`

**Comment by quangctkm9207** [comment]
Solution:
I found that when loading a new video, only use 
`play.setSource()`

Putting `player.stop()`or `player.reset()`  will cause the exception error.
Please remove them.

Note: Also, it is a bug that should be fixed.
