### ISSUE TITLE
Cannot inflate exception

### ISSUE THREAD

**Issue by asadwaheed1** [afollestad/easy-video-player#88]
- Easy Video Player version: `0.3.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy J5`

Using EasyVideoPlayer with simple Activity and Theme.Translucent.NoTitleBar gives inflate exception.

 
android.view.InflateException: Binary XML file line #195: Binary XML file line #47: Binary XML file line #47: Error inflating class android.widget.ImageButton
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                       Caused by: android.view.InflateException: Binary XML file line #195: Binary XML file line #47: Binary XML file line #47: Error inflating class android.widget.ImageButton
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:487)
                                                                          at android.app.Activity.setContentView(Activity.java:2400)
                                                                          at com.syncmate.android.activities.LogMeFreeOverlayAct.onCreate(LogMeFreeOverlayAct.java:47)
                                                                          at android.app.Activity.performCreate(Activity.java:6904)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       Caused by: android.view.InflateException: Binary XML file line #47: Binary XML file line #47: Error inflating class android.widget.ImageButton
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:807)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:868)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:487) 
                                                                          at android.app.Activity.setContentView(Activity.java:2400) 
                                                                          at com.syncmate.android.activities.LogMeFreeOverlayAct.onCreate(LogMeFreeOverlayAct.java:47) 
                                                                          at android.app.Activity.performCreate(Activity.java:6904) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class android.widget.ImageButton
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                          at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:706)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:774)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:807) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:868) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:487) 
                                                                          at android.app.Activity.setContentView(Activity.java:2400) 
                                                                          at com.syncmate.android.activities.LogMeFreeOverlayAct.onCreate(LogMeFreeOverlayAct.java:47) 
                                                                          at android.app.Activity.performCreate(Activity.java:6904) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                          at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:706) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:774) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                          at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:807) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:868) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:487) 
                                                                          at android.app.Activity.setContentView(Activity.java:2400) 
                                                                          at com.syncmate.android.activities.LogMeFreeOverlayAct.onCreate(LogMeFreeOverlayAct.java:47) 
                                                                          at android.app.Activity.performCreate(Activity.java:6904) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010082 a=-1}
                                                                          at android.content.res.TypedArray.getDrawable(TypedArray.java:883)
                                                                          at android.view.View.<init>(View.java:4244)
                                                                          at android.widget.ImageView.<init>(ImageView.java:150)
                                                                          at android.widget.ImageButton.<init>(ImageButton.java:85)
                                                                          at android.widget.ImageButton.<init>(ImageButton.java:81)
                                                                      	at and

**Comment by asadwaheed1** [comment]
Sorry to bother you. I got it fixed by changing built-in android theme Theme.Translucent.NoTitleBar to AppCompat Translucent

like this

 <style name="Theme.AppCompat.Translucent" parent="Theme.AppCompat.NoActionBar">
        <item name="android:background">#33000000</item> 
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:colorBackgroundCacheHint">@null</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowAnimationStyle">@android:style/Animation</item>
    </style>

Thanks guys for this library it helped me a lot.

**Comment by cindy-githut** [comment]
getting the same error android.view.InflateException: Binary XML file line #195: Error inflating class ImageView   but only on Android Version 4...5 and 6 are working perfectly fine

can anyone assist
