### ISSUE TITLE
Getting MissingFormatArgumentException

### ISSUE THREAD

**Issue by ananth10** [afollestad/easy-video-player#93]
For some videos . its not playing even though i have played .mp4 file. for your reference below i displayed error logs

```
java.util.MissingFormatArgumentException: Format specifier: 2F
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.util.Formatter.getArgument(Formatter.java:1111)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.util.Formatter.doFormat(Formatter.java:1076)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.util.Formatter.format(Formatter.java:1042)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.util.Formatter.format(Formatter.java:1011)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.lang.String.format(String.java:1554)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.lang.String.format(String.java:1528)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at com.wellness.tutor.videopalyer.BetterVideoPlayer.LOG(BetterVideoPlayer.java:882)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at com.wellness.tutor.videopalyer.BetterVideoPlayer.prepare(BetterVideoPlayer.java:330)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at com.wellness.tutor.videopalyer.BetterVideoPlayer.onSurfaceTextureAvailable(BetterVideoPlayer.java:575)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.TextureView.getHardwareLayer(TextureView.java:368)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16441)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16459)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17472)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16464)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16459)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16459)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16459)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16459)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16459)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17238)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.draw(View.java:17472)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16464)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:695)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:631)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.os.Looper.loop(Looper.java:158)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7229)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
04-06 11:48:30.553 28391-28391/com.wellness.tutor W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
04-06 11:48:30.563 28391-28391/com.wellness.tutor W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView) 
```

**Comment by ananth10** [comment]
Does anyone can tell me solution?
