### ISSUE TITLE
Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by geared554** [afollestad/easy-video-player#97]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Easy Video Player.
- [X] I have given my issue a non-generic title.
- [X] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `0.3.0`
#### 1
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Asus`
 - Device Name: `ZC553KL ZenFone 3 Max`
#### 2
 - Device OS version: `5.1.1`
 - Device Manufacturer: `Sony`
 - Device Name: `C6903 Xperia Z1`
#### 3
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi 4`
#### 4
 - Device OS version: `6.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `NEM-L51 Honor 5C`
#### 5
 - Device OS version: `5.1`
 - Device Manufacturer: `Highscreen`
 - Device Name: `Power Four`

###### Stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=328091, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/video:4082 flg=0x1 }} to activity {my.app/my.app.activity.RootActivity}: java.lang.IllegalStateException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3839)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3882)
       at android.app.ActivityThread.access$1300(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by java.lang.IllegalStateException
       at android.media.MediaPlayer.prepareAsync(MediaPlayer.java)
       at com.afollestad.easyvideoplayer.EasyVideoPlayer.setSourceInternal(EasyVideoPlayer.java:421)
       at com.afollestad.easyvideoplayer.EasyVideoPlayer.sourceChanged(EasyVideoPlayer.java:394)
       at com.afollestad.easyvideoplayer.EasyVideoPlayer.setSource(EasyVideoPlayer.java:246)
       at my.app.activity.PreviewVideoFragment.onActivityResult(PreviewVideoFragment.java:98)
       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
       at my.app.activity.RootActivity.onActivityResult(RootActivity.java:402)
       at android.app.Activity.dispatchActivityResult(Activity.java:6294)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3835)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3882)
       at android.app.ActivityThread.access$1300(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```
 
###### Reproduction Steps

Don't know. Received crash info via Crashlytics

###### Expected Result

No crash

###### Actual Result

Crash

**Comment by afollestad** [comment]
The `ResultInfo` part isn't part of this library.
